server:
  domain: localhost
  # port: 8080
# In environment variables it is SERVER_PORT

database:
  driver: postgres
  host: localhost
  # port: 5432
  name: shurl
  username: shurl
  password: password
