server:
  domain: localhost
  # port: 8080
  # In environment variables it is SERVER_PORT
  allow_login: true
  allow_registration: true
  allow_anonymous: false


database:
  driver: postgres
  host: localhost
  # port: 5432
  name: shurl
  username: shurl
  password: password
