networks:
  backend:
    driver: bridge

services:
##################################### PostgreSQL #####################################
  postgresql:
    image: postgres:18.2
    restart: unless-stopped
    container_name: postgresql
    security_opt:
      - "no-new-privileges:true"
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${SHURL_DATABASE_PASSWORD:?}
      POSTGRES_USER: shurl
      POSTGRES_DB: shurl
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d shurl -U shurl"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

##################################### Shurl #####################################
  shurl:
    image: ghcr.io/amieldelatorre/shurl:0.0.1
    restart: unless-stopped
    container_name: shurl
    security_opt:
      - "no-new-privileges:true"
    command:
      - "shurl"
      - "run"
      - "-f"
      - "/shurl/shurl.yaml"
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      DATABASE_PASSWORD: ${SHURL_DATABASE_PASSWORD:?}
    volumes:
      - ./shurl.yaml:/shurl/shurl.yaml:ro
    depends_on:
      postgresql:
        condition: service_healthy